export { FavoriteFilmsComponent } from "./favorite-films/favorite-films.component";
export { FilmListComponent } from "./film-list/film-list.component";
export { FilmCarouselComponent } from "./film-carousel/film-carousel.component";
export { FilmDetailsComponent } from "./film-details/film-details.component";
export { FilmFormComponent } from "./film-form/film-form.component";
export { FilmGridComponent } from "./film-grid/film-grid.component";
export { FilmSearchComponent } from "./film-search/film-search.component";
export { FilmTagsComponent } from "./film-tags/film-tags.component";
export { RecentFilmsComponent } from "./recent-films/recent-films.component";